name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to match your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change to your Python version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov playwright

    - name: Build Application
      run: |
        # Add commands to build your application
        # Example: python manage.py migrate

    - name: Run Unit Tests
      run: |
        pytest -m "not e2e"

    - name: Run Integration Tests
      run: |
        pytest -m integration

    - name: Generate Code Coverage Report
      run: |
        pytest --cov=myapp --cov-report=xml

  e2e:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change to your Python version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov playwright

    - name: Start Application
      run: |
        # Add commands to start your application for end-to-end tests

    - name: Run End-to-End Tests
      run: |
        pytest -m e2e

    - name: Stop Application
      run: |
        # Add commands to stop your application

