name: Automate Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - TestBranch  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6  # Change to your Python version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov playwright

    - name: Generate Code Coverage Report
      run: |
        pytest --cov=myapp --cov-report=xml
